const { cypressHtmlReporter } = require('cypress-html-reporter');

module.exports = (on, config) => {
  on('after:run', (results) => {
    return cypressHtmlReporter.generate({
      openReportInBrowser: true,  // Optional - Automatically opens the report in default browser
      reportFolder: 'cypress/report',  // Optional - Folder where reports will be saved
      jsonFile: 'cypress/results/output.json',  // Optional - Path to the JSON file generated by Cypress
    });
  });
};
